auto: true
pygments: true
paginate: 2
lsi: true
baseurl: /
img_url: /images

source:      .
destination: ./_site
plugins:     ./_plugins

permalink: /:categories/:title


#markdown: maruku
#Exclude: README.md
