auto: true
pygments: true
paginate: 2
lsi: true
baseurl: /
url: http://kun-g.github.io
img_url: /images

source:      .
destination: ./_site
plugins:     ./_plugins

permalink: /:categories/:title


#markdown: maruku
Exclude: README.md, ./sketch
title : Kun.G 的网络日志
#tagline: Site Tagline
#author :
#  name : Name Lastname
#  email : blah@email.test
#  github : kun-g
#  twitter : username
#  #weibo: @郭坤Freedom
#
